spring:
  data:
    neo4j:
      uri: bolt://node01.local:7687
      username: neo4j
      password: 86Ura4tw;

management:
  health:
    neo4j:
      enabled: true

graphql:
  spqr:
    gui:
      enabled: true